name: fastfood
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^17.2.1+2
  image_picker: ^1.0.8
  get_it: ^7.6.4
  number_text_input_formatter: ^1.0.0+8
  path: ^1.8.3
  path_provider: ^2.1.3
  provider: ^6.0.5
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
